package com.csl.datacore.entity;
// Generated Feb 6, 2013 9:34:05 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;
//import org.hibernate.envers.Audited;

/**
 * City generated by hbm2java
 */
//@Audited
@Entity
@Table(name = "city", catalog = "csl_sam", uniqueConstraints =
@UniqueConstraint(columnNames = "city_code"))
public class City implements java.io.Serializable {

    private Integer kode;
    private Integer version;
    private String cityCode;
    private String cityPhone;
    private String cityName;
    private String createdBy;
    private Date createdOn;
    private String updatedBy;
    private Date updatedOn;
    private String isActive;
    private String countryName;
    private String provinceName;
    private String description;

    public City() {
    }

    public City(String cityCode, String cityPhone, String cityName, String createdBy, Date createdOn, String updatedBy, Date updatedOn, String isActive, String countryName, String provinceName) {
        this.cityCode = cityCode;
        this.cityPhone = cityPhone;
        this.cityName = cityName;
        this.createdBy = createdBy;
        this.createdOn = createdOn;
        this.updatedBy = updatedBy;
        this.updatedOn = updatedOn;
        this.isActive = isActive;
        this.countryName = countryName;
        this.provinceName = provinceName;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "kode", unique = true, nullable = false)
    public Integer getKode() {
        return this.kode;
    }

    public void setKode(Integer kode) {
        this.kode = kode;
    }

    @Version
    @Column(name = "version")
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "DESCRIPTION", length = 65535)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "city_code", unique = true, length = 12)
    public String getCityCode() {
        return this.cityCode;
    }

    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    @Column(name = "city_phone", length = 12)
    public String getCityPhone() {
        return this.cityPhone;
    }

    public void setCityPhone(String cityPhone) {
        this.cityPhone = cityPhone;
    }

    @Column(name = "city_name")
    public String getCityName() {
        return this.cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    @Column(name = "created_by", length = 45)
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "created_on", length = 10)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name = "updated_by", length = 45)
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "updated_on", length = 10)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    @Column(name = "is_active", length = 1)
    public String getIsActive() {
        return this.isActive;
    }

    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    @Column(name = "country_name")
    public String getCountryName() {
        return this.countryName;
    }

    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    @Column(name = "province_name")
    public String getProvinceName() {
        return this.provinceName;
    }

    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }
}
